### ISSUE TITLE
Разработать диаграммы

### ISSUE THREAD

**Issue by LimitedTovar** [LimitedTovar/Kursach#1]
_1._ Архитектурная диаграмма 
_2._ Функциональная диаграмма UML (доработать)
_3._ Диаграмма последовательности UML
_4._ Концептуальная модель БД
_5._ Диаграмма пакетов UML

**Comment by martyushevleoned** [comment]
![Диаграмма пакетов](https://github.com/LimitedTovar/Kursach/assets/56407820/9aa79a10-6270-4039-bf37-b3643b22532a)
Диаграмма пакетов

**Comment by nowwnik** [comment]
![arhictec-diagram](https://github.com/LimitedTovar/Kursach/assets/144686984/67cfcf47-a7b9-4611-bbd2-f8c567ddfe4f)

Архитектурная диаграмма

**Comment by nowwnik** [comment]
![func-diagram](https://github.com/LimitedTovar/Kursach/assets/144686984/5cec9f4c-cabf-4711-a5bc-501dfed82a59)
Последовательности

**Comment by nowwnik** [comment]
![DB-diagram](https://github.com/LimitedTovar/Kursach/assets/144686984/8077c78b-7bbc-47b6-badb-ace302494de0)
БД

**Comment by LimitedTovar** [comment]
![Видение продукта(ФД) drawio](https://github.com/LimitedTovar/Kursach/assets/154826580/895a16ac-6315-4b6b-ac9b-d7e71e9d23db)
