### ISSUE TITLE
Задачи для раработчика

### ISSUE THREAD

**Issue by LimitedTovar** [LimitedTovar/Kursach#2]
1. Выбрать язык программирования
2. Описать стек-технологии
3. Реализация проекта
4. Тестирование продукта
5. Отчёт о выполнении

**Comment by martyushevleoned** [comment]
Язык: Java

Стек технологий:

Технологии предоставляемые фреймворком Spring:
•	spring-boot
•	spring-security

Внешние технологии:
•	PostgreSQL (База данных)
•	Hibernate (ORM)
•	Flyway (миграции)
•	Thymeleaf (шаблонизатор)
•	JavaScript (Запросы со стороны клиента)
•	Junit (Тестирование)
•	Lombok (Удобство разработки)

**Comment by martyushevleoned** [comment]
Скриншоты MVP проекта
![image](https://github.com/LimitedTovar/Kursach/assets/56407820/4e13fbc4-fdd1-46ba-8647-0f1e9cf03c8f)
![image](https://github.com/LimitedTovar/Kursach/assets/56407820/237bb81b-339f-4b72-a0ca-3e2d27a25f79)

**Comment by martyushevleoned** [comment]
Тестирование продукта:

Технологии:
1. SpringBootTest
2. MockMvc
3. JUnit

Перед исполнением тестов соответствующая база данных заполняется тестовыми данными с помощью flyway миграций.
Интеграционные тесты:
1. LoginTest
2. ProjectListControllerTest

**Comment by martyushevleoned** [comment]
MVP проекта реализовано!
