### ISSUE TITLE
Задачи проектировщика

### ISSUE THREAD

**Issue by LimitedTovar** [LimitedTovar/Kursach#3]
1. Разработать и оформить архитектурные диаграммы из issue #1 
2. Подготовить часть пояснительной записки
    2.1 Добавить диагрммы
    2.2 Написать требования к системному ПО (ОС, СУБД) 
    2.3 Заполнить раздел "Проектирование"
3. Добавить файлы в репозиторий
4. Отчёт о выполнении

**Comment by nowwnik** [comment]
Диаграммы добавлены в 1 issue

**Comment by nowwnik** [comment]
Требования к ПО: Установить Java 17 + PostgreSQL

**Comment by nowwnik** [comment]
Подготовил скрины и написал часть ПЗ

**Comment by nowwnik** [comment]
Создал папку диаграммы и добавил в неё скрины
